# 1. 服务端口配置
server.port=8080

# 2. 热重载配置 / 额外监听路径
spring.devtools.restart.enabled=true
spring.devtools.restart.additional-paths=src/main/java

# 3. 文件大小限制
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.web.resources.static-locations=/upload/

# SpringDoc 基础配置
# 接口扫描1
springdoc.packages-to-scan=com.example.helloworld.controller
springdoc.api-docs.enabled=true